[build]
# This assumes that the Zola site is in a docs folder. If it isn't, you don't need
# to have a `base` variable but you do need the `publish` and `command` variables.
base    = "personal"
publish = "public"
command = """
    wget -c https://github.com/gleam-lang/gleam/releases/download/v0.16.1/gleam-v0.16.1-linux-amd64.tar.gz -O - | tar -xz -C . &&
    cp -rp src/gleam/ffi.js static/generated_scripts/gleam/ffi.js &&
    ./gleam compile-package --src src --out static/generated_scripts --name personal --target javascript &&
    zola build
    """

[build.environment]
# Set the version name that you want to use and Netlify will automatically use it.
ZOLA_VERSION = "0.13.0"

# The magic for deploying previews of branches.
# We need to override the base url with whatever url Netlify assigns to our
# preview site.  We do this using the Netlify environment variable
# `$DEPLOY_PRIME_URL`.

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"